baseURL = 'https://renateroke.github.io/'
languageCode = 'nl-NL'
defaultContentLanguage = 'nl'
title = 'Renate Roke'
theme = 'hugo-theme-zen'

[Params]
  mobilemenu = true
  menuInHeader = true
 sectionPagesMenu = 'main'